version: "3.9"
services:
  keycloak-postgres:
    image: postgres:17
    container_name: keycloak-postgres
    restart: on-failure
    user: postgres
    environment:
      #      POSTGRES_USER: fampro
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
#      PG_DATA: /var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d postgres
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "5435:5432"
#    volumes:
#      - ./volumes/postgresql/data:/var/lib/postgresql/data/
    deploy:
      resources:
        limits:
          memory: 256M

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.1
    container_name: keycloak
    command:
      - start-dev
    environment:
      KC_DB_VENDOR: postgres
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: pass
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - type: bind
        source: ./volumes/keycloak/resources/realm-export/realm-export.json
        target: /opt/keycloak/data/import/realm-export.json
        read_only: true
    ports:
      - 8282:8080
    depends_on:
      - keycloak-postgres
#      keycloak-postgres:
#        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master"]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s