spring:
  application:
    name: FamPro-Main
  main:
    allow-bean-definition-overriding: true
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
management:
  endpoints:
    web:
      exposure:
        include: info
springdoc:
   swagger-ui:
      path: /swagger