spring:
  application:
    name: "FamPro"
    datasource:
      url: "jdbc:postgresql://localhost:5432/postgres"
      username: "postgres"
      password: "postkata"


# Hibernate properties

  jpa:
    properties:
      hibernate:
#        dialect: "org.hibernate.dialect.PostgreSQL10Dialect"
        show_sql: "true"
        hbm2ddl.auto: "update"

  mvc:
    hiddenmethod.filter.enabled: true