spring:
  application:
    name: "FamPro"
    datasource:
      url: "jdbc:postgresql://localhost:5432/postgres"
      username: "postgres"
      password: "postkata"


# Hibernate properties

  jpa:
    properties:
      hibernate:
#        dialect: "org.hibernate.dialect.PostgreSQL12Dialect"
        show_sql: "true"
        hbm2ddl.auto: "update"
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
  mvc:
    hiddenmethod.filter.enabled: true