spring:
  flyway:
    enabled: true
    default-schema: fam_pro
    locations: "db/migration"
    out-of-order: true
  application:
    name: famPro-storage
    datasource:
      username: postgres
      password: pass
      url: jdbc:postgresql://localhost:5433/FamPro_db?currentSchema=${spring.application.datasource.default-schema}
      default-schema: fam_pro
  jpa:
    properties:
      hibernate:
        #        dialect: "org.hibernate.dialect.PostgreSQL10Dialect"
        show_sql: "true"
        hbm2ddl.auto: "update"
        default_schema: fam_pro
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
  mvc:
    hiddenmethod.filter.enabled: true

server:
  port: 7777
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  server:
    enable-self-preservation: false
management:
  endpoints:
    web:
      exposure:
        include: info
springdoc:
  swagger-ui:
    path: /swagger