spring:
  application:
    name: famPro-integration

  telegram: xxxxxxxxxx:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  mail:
    host: smtp.mail.ru
    hostInput:  imap.mail.ru
    port: 465
    portInput: 993
    username: kyevt@bk.ru
    password: XXXXXXXXXXXXXXXXXXX
    mailbox: inbox
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: "*"
        imap:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: "*"


server:
  port: 9898
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
logging:
  level:
    root: INFO
    org.springframework.integration: DEBUG

