spring:
  application:
    name: famPro-notification
  mail:
    host: smtp.mail.ru
    port: "465"
    username: kyevt@bk.ru
    password: xxxxxxxxxxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust:  "*"

server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}


